name: Arduino CI

on: [push]

jobs:
  build-sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
