name:  ESP32 board on CI
on: [push, pull_request]
jobs:
  build-sketch:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Build on Arduino CLI
         run: bash ci/build-arduino.sh
       - name: Setup Arduino CLI
         uses: arduino/setup-arduino-cli@v1.0.0
       - name: upload
         uses: actions/upload-artifact@master
         with:
          name: app-version-${{ env.VERSION }}
          path: app-${{ env.VERSION }}.exename:ESP32 board on CI
 
       - name: Install platform
         run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
       - name: Compile Sketch
         run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./blink
  

 
   
 
