name: Android CI
on: [push]
jobs:
  build-sketch:
    runs-on: ubuntu-latest
    steps: 
 
      - name: Fetch sketch dependencies
        run: |
          arduino-cli core update-index --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli core install esp32:esp32 --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli lib install "Smartcar shield"
      - name: Build sketch
          run:|  
          arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 arduinoSrc/WebServer/WebServer.ino
