
 - name: Fetch sketch dependencies
     run: |
          pip3 install pyserial
          arduino-cli core update-index --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli core install esp32:esp32 --additional-urls "https://dl.espressif.com/dl/package_esp32_index.json"
          arduino-cli lib install "Smartcar shield"
 - name: Build sketch
     run: |  
          arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 arduinoSrc/WebServer/WebServer.ino
