name:  ESP32 board on CI
on: [push, pull_request]
jobs:
  build-sketch:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@v2
 
             
       - name: upload
         uses: actions/upload-artifact@master
         with:
          name: app-version-${{ env.VERSION }}
          path: app-${{ env.VERSION }}.exename:ESP32 board on CI
      
     
       - name: Get Python3
         uses: actions/setup-python@v1
         with:
          python-version: '3.x'
     
      
       - name: Compile Sketch
         run: |
          arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 arduino/SmartcarWebserver/SmartcarWebserver.ino
          arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 arduino/SmartcarWebserverWithClass/SmartcarWebserverWithClass.ino
          arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 arduino/SmartcarWebserverTestable/SmartcarWebserverTestable.ino         
      
  

 
   
 
